### PR TITLE
Add deployment docs

### LINKED ISSUE #5: Get a VM to deploy loot and future UIs
1. Get a wmflabs vm from wikitech (as big as allowed) for the research project
2. Add deployers (Me + Sam for example)
3. Configure bare repo with post receive hooks for git deployments.
4. Deploy

### PR DESCRIPTION
**Pull request by joakin**
I've created http://reading-web-research.wmflabs.org and set up git deployments.

See `docs/Deployment.md` and see if it makes sense.
- Now we can deploy by just running `git push wmflabs master` after following the configuration docs.

Example http://reading-web-research.wmflabs.org/slim/Barack%20Obama

Closes #5

### CODE REVIEW

**Comment by joakin** [comment]
@phuedx One issue with the post-receive hook is that after pushing you need to ctrl+c out of it, not sure why (i'm running the server with `nohup npm run prod &`)

``` sh
#!/bin/bash
while read oldrev newrev ref
do
    if [[ $ref =~ .*/master$ ]];
    then
        GIT_WORK_TREE=/home/loot/loot
        echo "Master ref received.  Deploying master branch to production..."
        git --work-tree=$GIT_WORK_TREE --git-dir=/home/loot/loot.git checkout -f
        echo "Repository checked out. Killing node processes..."
        killall node
        echo "Installing dependencies..."
        cd "$GIT_WORK_TREE"
        npm install
        echo "Starting server..."
        nohup npm run prod &
    else
        echo "Ref $ref successfully received.  Doing nothing: only the master branch may be deployed on this server."

    fi
done
```

Ideally this would be an upstart service run with foreman/pm2/nodemon or something like that, for the moment I can't be bothered with that.

**Comment by joakin** [comment]
@phuedx How should we keep track of the post-receive hook? Should we add it to the repo somewhere?

**Comment by phuedx** [comment]
@joakin I'm fine with keeping code and how it's deployed in the same repository as long as we keep the two concerns well separated.

**Comment by phuedx** [comment]
> Ideally this would be an upstart service run with foreman/pm2/nodemon or something like that, for the moment I can't be bothered with that.

See [Using nodemon with forever](https://github.com/remy/nodemon/blob/master/faq.md#using-nodemon-with-forever) for some interesting info.

**Pull request merged**
