### PR TITLE
Add benchmark routes

### PR DESCRIPTION
**Pull request by phuedx**
See [Reading/Web/Projects/A_frontend_powered_by_Parsoid/HTML_content_research ](https://www.mediawiki.org/wiki/Reading/Web/Projects/A_frontend_powered_by_Parsoid/HTML_content_research) for context.
### TODO
- [x] `/benchmarks/restbase/:title`
- [x] `/benchmarks/mediawiki/:title`
- [x] `/benchmarks/mobileview/:title`
- [x] `/benchmarks/loot/:title?transforms=...`

### CODE REVIEW

**Comment by jdlrobson** [comment]
In my measurements, first paint on 
https://reading-web-transforms.wmflabs.org/benchmarks/loot/Barack%20Obama?transforms=nodatamw 
is lower than
https://reading-web-transforms.wmflabs.org/benchmarks/loot/Barack%20Obama?transforms=noimages|nodatamw

which makes no sense to me and is causing me much confusion.
I'm seeing a first paint of 41.961s [http://www.webpagetest.org/result/151223_K0_2W2/6/details/ ] compared to 65s [http://www.webpagetest.org/result/151222_F6_14KS/4/details/] but in the opposite direction to which I'd expect

Any idea why that might be? Is there some caching stuff going on?

**Comment by joakin** [comment]
@jdlrobson In the images case you are also stripping navboxes, references, and datamw which makes the content be 60kb. In the no-images case, you are only stripping data-mw, which makes the content around 300Kb, which accounts for the longer download and longer first-paint & visually complete.

**Comment by joakin** [comment]
@jdlrobson I've run the test with the same transforms, and it makes more sense and it shows that images only lead to a marginal 3 seconds on start render http://www.webpagetest.org/result/151223_J5_D4B/1/details/

From 35s (no images) to 38s (with images). That makes sense, right?

**Comment by joakin** [comment]
Nice!

**Comment by jdlrobson** [comment]
To be clear I'm trying to compare two pages the only difference being that in one of them images are scrubbed. Given  there are lots of incomplete webpagetests I've been told not to use median but best case and the numbers do not seem to add up

**Comment by phuedx** [comment]
@jdlrobson You haven't really made things clearer with that comment. Which tests are incomplete and which numbers don't add up?

**Comment by phuedx** [comment]
@jdlrobson In [your comment](https://github.com/joakin/loot/pull/47#issuecomment-166774008) the transform URLs, timings, and associated WPT URLs you've provided don't match up. Could it be the case that you're looking at the wrong results? 😇

**Comment by jdlrobson** [comment]
On phone right now but I'll attempt a better job at explaining when I'm in front of my laptop :)

**Comment by jdlrobson** [comment]
So I updated https://www.mediawiki.org/wiki/Reading/Web/Projects/A_frontend_powered_by_Parsoid/HTML_content_research#Webpagetest_report_.28browser_loading_time.29
The results are more like I expected.
Interestingly stripping images as well as the HTML doesn't have much impact which was a little of a surprise but I guess it makes sense - as the HTML is much smaller there is less competition. Hopefully this data will do.

**Pull request merged**
